### ISSUE TITLE
Unable to reach ELB

### ISSUE THREAD

**Issue by subhadipbhatta** [mendhak/selenium-grid-ecs#1]
I have followed step by step. However unable to reach the ELB DNS. Are you sure we dont need to make any other changes other than what mentioned in the website?

**Comment by mendhak** [comment]
I just reran it to make sure, yep - everything working as expected and I only had to modify the top 4 `variable`s in the main.tf.  

When you say reach, do you mean you're unable to browse to it?  Is everything actually created without problem (ALB, ECS Service, Target Group)

Did you enter `your_ip_addresses` correctly? If it's a single IP it should end with a /32, like `xx.xx.xx.xx/32`.  You can try making it wide open for a few minutes, set it to `0.0.0.0/0` and see if it's reachable, then set it back to your own IP.

**Comment by subhadipbhatta** [comment]
It still doesn't work. I think the root cause of the issue may be - the clusters are not getting instantiated. Here is the screenshot 
![image](https://user-images.githubusercontent.com/29129640/98447263-3e966300-20d8-11eb-8c1a-3d8323013c0f.png)

When I deep dive, I see the root cause as - `

Status reason | CannotPullContainerError: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for
-- | --`
Is it an issue with the root table?
I have used both open internet 0.0.0.0/32 and my private ip x.x.x.x/32 as **your_ip_addresses**  - however no luck.

Let me know if you want to have a zoom call to debug.

**Comment by mendhak** [comment]
Yep that's a clue.  It likely means your private subnet has no route to the internet.  So when the fargate container spins up, it's trying to pull from Docker Hub and failing.  Anything you create in your private subnet, currently, will be unable to reach the internet.  

So just to be clear, this is a problem with your VPC configuration.  Everyone has a different configuration that's why I excluded it from the Terraform setup.  I'm not available for troubleshooting but I can give some pointers.   

The most common way to get your connectivity working is to create a NAT Gateway in your _public_ subnet.  Then in your _private_ subnet's route table, you add a route 0.0.0.0/0 that points at the above NAT Gateway.  Once you do that, Fargate has the ability to pull containers from the internet and use them.

**Comment by subhadipbhatta** [comment]
Thanks. That helps. I did that and now I see the services are UP and RUNNING. However I am constantly getting server side error (503) when trying to access the ELB.

**Comment by mendhak** [comment]
Wait a bit after the containers are created, the selenium startup process is really slow. Wait 15 minutes then try again.

In the AWS console you should see that the target group is targeting an ip address.

**Comment by mendhak** [comment]
503 means you're reaching the ALB, so it's just the onwards part which needs to work now

**Comment by subhadipbhatta** [comment]
Followed your instruction - able to hit the ELB, however none of the nodes are accessible. Though the equivalent tasks are up and running in ECS container.

So... this is what I have done...
1. Created a VPC (CIDR - 10.0.0.0/16)
2. Created 2 public subnets in us-east-1a and 1b (cidr / 24)
3. created 1 private subnet in us-east-1b (cidr /24)
4. The main route table is pointed to public internet (0.0.0.0/0) through IGW and associated with public subnets
5.  Other route table is pointed to public internet (0.0.0.0/0) through nat gateway which was created in public subnet1.

Post that, I have initated, planned and applied the terraform code by changing the variables.

I have still kept your_ip_addresses = 0.0.0.0/0 since this is a POC.

Here is the outcome: 
![image](https://user-images.githubusercontent.com/29129640/98457309-a5e4ff00-213a-11eb-86e6-d55ec97a94cb.png)

What am I missing?

**Comment by mendhak** [comment]
Hmm.  All the steps you've mentioned are correct.  So if you can see that page, that means the Selenium Hub container is working fine.  It is now waiting for the browsers to check in.  

So at this point I think have a look at the browsers (nodes), why are they unable to find the main Selenium hub?  Do those tasks have `HUB_HOST` defined?  It should be set to `hub.selenium`.  Next go look at Route 53, is there a zone created there.  Search for the service Cloud Map, and in there, you should see a 'selenium' service, does its health checks look OK?

**Comment by mendhak** [comment]
Did this work for you?

**Comment by subhadipbhatta** [comment]
Nope

**Comment by subhadipbhatta** [comment]
Did u find a solution to the problem. I insist a quick screen share session to resolve this since I have passed the same to some of my colleagues and they are facing the same issue as well. Guess its an issue with the VPC config

**Comment by subhadipbhatta** [comment]
I am getting the following message:
![image](https://user-images.githubusercontent.com/29129640/102416079-0ffc8980-3fae-11eb-80c1-7670060c56ad.png)

**Comment by mendhak** [comment]
I'm wondering if this is related to DNS.  Does your VPC use your own organisation's DNS instead of AWS Route 53's?   That would explain this - if `hub.selenium` cannot be resolved then the request might be going somewhere else, which is unaware of this made-up TLD.  

To find out you can have a look at DHCP Option Sets under your VPC's configuration, if there are any DNS related entries in there.  If nothing in DHCP Option Sets, have a look at Route53 Resolvers.  There may be something there taking on all the DNS requests.  That's as far as my knowledge goes. 

I'm unable to join any calls/screenshares, best I can do is respond in this thread.  

Did you also [look through the details in my last post?](https://github.com/mendhak/selenium-grid-ecs/issues/1#issuecomment-723578724).

**Comment by subhadipbhatta** [comment]
Yes cloud map shows it to be healthy:
![image](https://user-images.githubusercontent.com/29129640/102524968-84870500-404e-11eb-9cbc-f88efed9c192.png)


Also - I have checked DHCP connection. I am not so familiar with DHCP, however I do see DHCP gets created when we create a VPC:
![image](https://user-images.githubusercontent.com/29129640/102525114-b304e000-404e-11eb-82eb-f134ffc520c8.png)

**Comment by mendhak** [comment]
I just reran from scratch and I got similar error logs to yours but after about a minute it's able to find the main hub.  Did you leave the nodes alone for a little while?  

![image](https://user-images.githubusercontent.com/746276/102528032-e454ce80-4095-11eb-963c-0468ffd81450.png)


I looked at your Cloud map and DHCP screenshots and everything looks same as mine.

**Comment by mendhak** [comment]
Just had another thought.  Security groups.  If the nodes can't reach the hub, is something blocking the nodes?  Well it could be an SG rule.   Here's what gets created for me.  Does it match yours?  I've blanked out some VPC ID details.  

![image](https://user-images.githubusercontent.com/746276/102528827-f84d0000-4096-11eb-81be-92a349a54247.png)


For the nodes to hub communication, the 4444 and 5555 are important.  The port 80 is just for your own testing and shouldn't affect the nodes.

**Comment by mendhak** [comment]
And of course make sure the SG did get applied to the LB and the seleniumhub.  Here's a screenshot (with some redacted) of the load balancer. 

![image](https://user-images.githubusercontent.com/746276/102529219-81643700-4097-11eb-8ff2-c77aeb37411d.png)


And here's the seleniumhub service itself, with the same security group applied.  

![image](https://user-images.githubusercontent.com/746276/102529349-a789d700-4097-11eb-8ab9-18a0fd3c9ce0.png)

**Comment by subhadipbhatta** [comment]
Fortunately I was able to resolve the issue but not in a convincing way. This is what I did -
1. post creating the ECS clusters I have gone to the seleniumchrome and firefox tasks individually.
2. Picked up the private IP for the hub
3. replaced hub.selenium in the respective tasks and updated with the latest IP.
4. Given required time to establish the connection between hub and nodes.
It started working from then on....
![image](https://user-images.githubusercontent.com/29129640/102542645-f4a18500-4066-11eb-85cf-89cff5a96ffd.png)

**Comment by mendhak** [comment]
That highly likely sounds like a private DNS issue.  It still feels like private DNS zones aren't working then.  May be a Route 53 Resolver, or something else I'm not suretbh. A way you could verify this, but it's quite some effort, is to create an EC2 in that VPC and try to `dig hub.selenium` - if you get no answer back then it's just proving the DNS problem.  

If you're looking for a more 'repeatable' solution, maybe you need to use public DNS instead of private DNS.  Instead of a private DNS namespace, like this: 

https://github.com/mendhak/selenium-grid-ecs/blob/d8e93a716a334c7c91129fc2ab9c904dd90cff51/main.tf#L134-L138

replace it with a [public DNS namespace](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/service_discovery_public_dns_namespace) - which in turn will require you to have a public domain in place, and the hub would then be registered against something like `hub.selenium.example.com` pointing at `10.x.x.x`.   Whether you can do this really depends on your company's policies though.

**Comment by subhadipbhatta** [comment]
Closing the issue. since I had to set DNS hostnames = Enabled. Done that and its working.

**Comment by zealsara** [comment]
> Closing the issue. since I had to set DNS hostnames = Enabled. Done that and its working.

Thanks a lot @subhadipbhatta

**Comment by JyotiPrakashMallick** [comment]
@subhadipbhatta how you resolved this, I am in similar situation.

**Comment by shivachinthala** [comment]
@mendhak : First of all, thank you so much for the very detailed explanation of the complete setup. we were able to setup the Selenium grid4 using ALB. 

We have one challenge with On-prem node registration of with this setup. The complete network connection between on-prem and AWS VPC Config fine, where we are able to make PING, Test-NetConnection, tracert all are fine but still the node registration fails. 

Here we have used the hub as "Route 53 DNS record" even we observed that with in the VPC the ECS chrome tasks (node) are getting failed if we go with Route53 DNS record instead of CloudMap. So is this the same reason for on-prem node failure ?

Note: R53+NLB (VPC Private subnets)+ECS Fargate (VPC private subnets) without Cloudmap. With this setup, the on-prem node able to make successful registration. 

Could you please help us with suggestion on "whether we can use the ALB based setup to attach the on-prem node?" if there are any possibilities could you please let us know. Thank you :)

**Comment by mendhak** [comment]
Oof it's been a good few years since I've used this setup so I my memory is fuzzy. 

If I've understood what you're saying correctly... the setup works if you use an NLB but doesn't work if there's an ALB? Other than the LB, the setup is exactly the same: Route 53, ECS/EC2, all the same.

If that's the case, then I'd investigate the ALB setup. Although you've mentioend ping and test-netconnection (which I assume is like `nc` command), it will depends on which ports you tested. Try connecting from the node to the ALB 4444 and ensure that's forwarding to the hub's 4444 port.

Another thing could be security groups; with NLBs, the security group rules are those of the target hub. With ALBs, there are security groups on the ALB and also the target hub. Ensure that the target hub allows traffic from the ALB's IP address. 

I'm pointing this out because in the Terraform I see that the hub is being created in the public subnet, but your working example is all private subnets. So there could be NACL rules at play here too, or route table. For example what if the node registration request reaches the hub but the response is going out over a NAT Gateway. So you could try moving that hub into the private subnet.
