### ISSUE TITLE
Nodes giving NULL value instead of container IP 

### ISSUE THREAD

**Issue by Varun-km0392** [mendhak/selenium-grid-ecs#2]
Hey Mendhak,

I was experimenting with selenium grid and came across your solution. When i tried to implement I saw that all the resources are created and its giving me an URL output to connect the grid/console. Till here its good, the issue starts when the nodes are trying to register to the HUB, instead of the private IP of the container its getting attached with a null value ,eg remotehost= http://null:5555

Could you please help me out on this.

regards
Varun KM

![image](https://user-images.githubusercontent.com/82015758/113663103-0e72e080-96c7-11eb-80c6-e3af80867c8a.png)

**Comment by mendhak** [comment]
If it's sending 'nothing', that might mean that the startup command to get its own IP isn't working.  You can try a few things. 

FIrst try to compare your task to my screenshot here.  I've hidden some details but the rest should be fine.  Does your chrome task for example have an ENI, an IP Address?

![image](https://user-images.githubusercontent.com/746276/113774948-e6639b80-971f-11eb-8b78-2b8273217cfd.png)


The second thing you can try is to manually edit the task definition and enable logging.  Then change the command, add an `echo $PRIVATE` in the set of commands so that the container outputs to Cloudwatch.  Or for more troubleshooting, change the command to just do  `curl http://169.254.170.2/v2/metadata` and the full output should be sent to Cloudwatch.  There you can see if anything has changed, or if it's not matching the JSON output and getting the value out.  

The metadata endpoint is described here:  https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint-v2.html

**Comment by Varun-km0392** [comment]
Hi Mendhak,

Thank you so much for your quick response, I am currently running a workload of having 5 chrome nodes running 30 instances each and 5 firefox nodes running 50 instances each which is supported by 2 hubs. 

I have made more changes in the config to support the above, below is what fixed for me

curl -s http://169.254.170.2/v2/metadata | jq -r '.Containers[0].Networks[0].IPv4Addresses[0]'

I changed from Containers[1] to Containers[0] as Containers[1] was giving a NULL value . Could you please suggest if having Containers[0] can affect in any way and any inputs as to why Containers[1] is failing whereas it was working perfectly fine before.

**Comment by mendhak** [comment]
Very interesting, OK so [0] worked for you.  I think you should be fine with [0], no problems.  I can't remember now why I put [1] - I must have been trying to get it to work and [1] was giving the IP address, while [0] wasn't, perhaps something has changed.  The best way to know would be to see the full curl output of that metadata endpoint.  

But anyway it's probably worth me adding a note to try [0] if [1] doesn't work.  That way future people can try that out.

**Comment by Varun-km0392** [comment]
Yep, Thank you for the help Mendhak. The curl output was coming through with all the data thats how i figured out that it must be related to the jq and tried changing those params which in the end solved.

Again thank you for the help and this solution. It acts as a beautiful template to build on.
